### ISSUE TITLE
Contributor / Author Detail (Listings) Page

### ISSUE THREAD

**Issue by royboy789** [TheWPCrowd/the-wp-crowd-theme#11]
Contributor page notes:
- Make it mandatory for everyone to write at least 75 words for their bio. If you cannot write 75 words, you don’t deserve to be a contributor.
- Photo, name, and position (e.g., “senior editor”) should be larger than the main contributors page. I suggest sizes for all three to be similar to what I put in the sample (for the desktop version, obvi!).

RIGHT SIDEBAR NOTES
- On the main contributor page, a contributor’s location is only indicated by the city. But, for the profile page, it is city, state, country. I don’t think it’s necessary to link it (to a map) on this page. Just text will do. That is good for SEO as well.
- For a better user experience and in order for everyone to get an SEO boost, on the profile page you are allowed to put descriptive words / keywords next to the icons. 

Here is the order (for programming purposes):
- If nothing is filled in, no icon appears.
- If a URL is filled in the form field for a social media platform, the name of the social media platform appears next to the icon (e.g. “Facebook”). 
- If a URL is filled in the form field for a social media platform AND there is username associated with it, the username appears (e.g. @brianrotsztein will appear instead of “Twitter”). Note that many platforms will not have a username (e.g., LinkedIn).
- If a URL is filled in the form field for a website, the URL appears (e.g., “www.rotsztein.com”).
- If a URL is filled in the form field for a website AND a description is added to the form field, the description appears (e.g., “Brian’s Hub” instead of “www.rotsztein.com”).
- Please indicate in the back end whether you need “http” or not when you fill in each form field

THUMBNAILS
- Each video/podcast/“blog post” is created in the fashion of an article. I’ll describe that more later. The point here is that since that is the case, you cannot divide “videos” and “blog posts” in an individual’s profile. They all go together. What I strongly suggest (see design) is to just have a button to filter articles from videos. 
- I did not add this to the design but you can add a pipe to the right of “VIDEOS & ARTICLE | ARTICLES ONLY |  VIDEOS ONLY” and then put a link to AUDIO ONLY which then calls a list of all the podcasts the contributor is in. I think the audio files should be the only type of file that is NOT presented like all the other ones (e.g., “thumbnail box”). I suggest that I create a “style” that looks something like how iTunes looks when you download podcasts. The familiarity is good for user experience. This will also make it clearly distinct. What I mean is that each video will be embedded into an article-style format. If there was no video, and instead we only had an audio file, the audio file would take center stage at the top of the article. Since we DO have video, the audio file should be more distinct. We can link the audio file under the video and above the text on an article page. But, to make it easy to download audio files, I can make a separate page (in the style of iTunes podcast downloads). 
- All thumbnail images must be the exact same size
- The image for the thumbnail does not have to be a face (aka screenshot from the Google Hangouts session). Many should start being images (stock photos, etc) that are thematically related.

CONCEPTUAL IDEA
- Since each video/podcast/article is created in the fashion of an article, I suggest no longer using the term “blog” and to stop thinking of the site as a blog. It’s more of a magazine, a “daily,” and a newspaper in a sense. Saying “The WP Crowd” is a magazine makes more sense to me than to call it a “blog.”

**Comment by ChrisFlannagan** [comment]
How/Where do we leave our bio? I saw the template in the theme but I'm thinking I'm missing a plugin or something because I get a "get_field()" function missing error

**Comment by royboy789** [comment]
@ChrisFlannagan You need Advanced Custom Fields Installed.

**Comment by ChrisFlannagan** [comment]
@royboy789 if we aren't sharing a database for working on this will it really matter if I add my bio to my dev install? Should I just add it somewhere in the staging site? I tried logging in there and my account isn't attached to the staging one.

**Comment by royboy789** [comment]
@ChrisFlannagan no, we'll worry about content once the site goes live. I'm not dealing with porting the DB over
