### ISSUE TITLE
Pick out fonts, implement.

### ISSUE THREAD

**Issue by royboy789** [TheWPCrowd/the-wp-crowd-theme#18]
Find fonts TypeKit.com 
Let me know which font for what and I'll put it into the sass and get the JS file enqueue'd from TypeKit

**Comment by royboy789** [comment]
For @mathetos

**Comment by mathetos** [comment]
@royboy789 What's your thought on this typography? All fonts are variations of Montserrat.

![typography-preview](https://cloud.githubusercontent.com/assets/930724/16031545/45c24628-31b1-11e6-9468-89e3e8ae7bf6.jpg)

**Comment by mathetos** [comment]
Except the Sidebar Titles are the LOGO font DS-Digital.

**Comment by royboy789** [comment]
👍  make it so

**Comment by mathetos** [comment]
https://github.com/TheWPCrowd/the-wp-crowd-theme/commit/12bcdc15f3af54e85c873e24450905040f53a071 resolves this.
