### ISSUE TITLE
Installing / Configuring Epoch once we launch

### ISSUE THREAD

**Issue by royboy789** [TheWPCrowd/the-wp-crowd-theme#19]

**Comment by mathetos** [comment]
Epoch = https://wordpress.org/plugins/epoch/
Social Commenting = https://wordpress.org/plugins/postmatic-social-commenting/

**Comment by mathetos** [comment]
Actually, @royboy789 I can install and setup, but for Social Commenting it's probably better if you use your WPCrowd Social accounts to configure the social commenting rather than me creating the API keys through my personal account.

**Comment by mathetos** [comment]
What happened to this? Looks like Epoch has been disabled? We CAN'T do Disqus... it's a crime.

**Comment by royboy789** [comment]
As we discussed.. Postmatic was used, Epoch didn't want to work, so we had to go with something else, but def not Disqus.

**Comment by mathetos** [comment]
Cool.
