### ISSUE TITLE
missing featured image messes up design

### ISSUE THREAD

**Issue by ghost** [TheWPCrowd/the-wp-crowd-theme#32]
if a post gets published without a feature image, the design gets thrown out of whack. 

![screen shot 2016-06-28 at 7 49 01 pm](https://cloud.githubusercontent.com/assets/577207/16435011/7462728c-3d69-11e6-9d1f-7e951ee18665.png)

**Comment by royboy789** [comment]
going to say this is a non-issue.. i know we SHOULD have a fallback, but featured images are too important to just be forgotten or not implemented.. even if its just the WP crowd logo
