### ISSUE TITLE
contributor map

### ISSUE THREAD

**Issue by ghost** [TheWPCrowd/the-wp-crowd-theme#35]
can we get the map to auto focus to include all the pirate points, or something less random?

also, the mockups called for it to be different style wise
![screen shot 2016-06-28 at 7 57 00 pm](https://cloud.githubusercontent.com/assets/577207/16435202/9609f7ba-3d6a-11e6-8ae2-57c459cb30c2.png)

**Comment by royboy789** [comment]
Styling addressed in @thisismyurl's latest Merge into v2.0.0.. but we need to zoom & center dynamically.

**Comment by royboy789** [comment]
Rolling in #45
