### ISSUE TITLE
poor wrapping on location title

### ISSUE THREAD

**Issue by ghost** [TheWPCrowd/the-wp-crowd-theme#37]
looking at Andrew's location name, the text wraps outside the pin. can we make the text smaller, or ensure the text is aligned properly

![screen shot 2016-06-28 at 7 58 00 pm](https://cloud.githubusercontent.com/assets/577207/16435224/ca6e5bae-3d6a-11e6-9db7-c81242f1ac55.png)

**Comment by royboy789** [comment]
This is based on user input in their profile.. unlike the names which i can force a line break, can't do that with the location... closing for now, unless you think of a solution

**Comment by ghost** [comment]
If you get the author name into a variable, you can to an explode() with a <br> on the implode()
