### ISSUE TITLE
forced spacing for the date

### ISSUE THREAD

**Issue by ghost** [TheWPCrowd/the-wp-crowd-theme#38]
the forced spacing for the index item height is causing the date to be irrelevant, we can pull it up and leave the white space under the list.
![screen shot 2016-06-28 at 8 02 55 pm](https://cloud.githubusercontent.com/assets/577207/16435300/5329d3a6-3d6b-11e6-9e2f-50492a405d59.png)

**Comment by royboy789** [comment]
fixed in #33
