### ISSUE TITLE
video thumbnails are too similar

### ISSUE THREAD

**Issue by ghost** [TheWPCrowd/the-wp-crowd-theme#39]
the video thumbnails all look the same, let's look at adding a custom image to the posts to make them look better 

![screen shot 2016-06-28 at 8 06 30 pm](https://cloud.githubusercontent.com/assets/577207/16435365/d38f68ee-3d6b-11e6-81c3-02f9d928e781.png)

**Comment by royboy789** [comment]
These are brought in from YouTube, creating the content and video editing doesn't allow me enough time to also do a Photoshop for each video. Lets discuss this again later when I have more time to dedicate.
