### ISSUE TITLE
fixed heights are messing with multi line titles

### ISSUE THREAD

**Issue by ghost** [TheWPCrowd/the-wp-crowd-theme#41]
fixed heights are messing with multi line titles
![screen shot 2016-07-07 at 11 02 00 am](https://cloud.githubusercontent.com/assets/577207/16657929/5023ecbe-4432-11e6-96f8-d434701c0941.png)

**Comment by royboy789** [comment]
have a link to this?

**Comment by ghost** [comment]
It was on the homepage, but it looks like you forced heights so it's okay now
