### ISSUE TITLE
Social Hearts Plugin / Functionality

### ISSUE THREAD

**Issue by royboy789** [TheWPCrowd/the-wp-crowd-theme#6]
Not sure to code or to plugin download this up. We want "hearts" to be total shares of a post / podcast.

We can use a post_meta counter as a last resort tied into (any) social share

**Comment by royboy789** [comment]
Brian sent me this code, might want to look into it:
https://gist.github.com/royboy789/6adc98b85f6bd270b3fa963e8617b984

**Comment by andykillen** [comment]
The gist is out of date. Twitter stopped using this api about 5 months ago

but however I will take on the social sharing. 

Would it not be better for videos and podcasts to show the play count?

**Comment by andykillen** [comment]
When I say stopped. The stopped allowing people access to the share count information.

**Comment by royboy789** [comment]
@andykillen that is fine, we need to find a way to combine the rest easily. Addthis used to this well (on the current site) but its not working anymore, not really sure why. Videos and Podcasts are the same thing.
